planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
start_state_max_bounds_error: 0.1

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0

left_arm:
  planner_configs:
    - RRTConnectkConfigDefault
  projection_evaluator: joints(openarm_left_joint1,openarm_left_joint2)
  longest_valid_segment_fraction: 0.01

right_arm:
  planner_configs:
    - RRTConnectkConfigDefault
  projection_evaluator: joints(openarm_right_joint1,openarm_right_joint2)
  longest_valid_segment_fraction: 0.01

right_gripper:
  planner_configs:
    - RRTConnectkConfigDefault
  projection_evaluator: joints(openarm_right_finger_joint1)
  longest_valid_segment_fraction: 0.01

right_arm_with_gripper:
  planner_configs:
    - RRTConnectkConfigDefault
  projection_evaluator: joints(openarm_right_joint1,openarm_right_joint2)
  longest_valid_segment_fraction: 0.01

bimanual_arms:
  planner_configs:
    - RRTConnectkConfigDefault
  projection_evaluator: joints(openarm_left_joint1,openarm_right_joint1)
  longest_valid_segment_fraction: 0.01
