# Default initial positions for right_piper_tomato's ros2_control fake system

initial_positions:
  right_joint1: 0
  right_joint2: 0
  right_joint3: 0
  right_joint4: 0
  right_joint5: 0
  right_joint6: 0
  right_joint7: 0
  right_joint8: 0